// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	Alias                string   `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	PubKey               string   `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Cipher               string   `protobuf:"bytes,3,opt,name=cipher,proto3" json:"cipher,omitempty"`
	EncryptedPrivKey     string   `protobuf:"bytes,4,opt,name=encrypted_priv_key,json=encryptedPrivKey,proto3" json:"encrypted_priv_key,omitempty"`
	Iv                   string   `protobuf:"bytes,5,opt,name=iv,proto3" json:"iv,omitempty"`
	Mac                  string   `protobuf:"bytes,6,opt,name=mac,proto3" json:"mac,omitempty"`
	Version              uint32   `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Account) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *Account) GetCipher() string {
	if m != nil {
		return m.Cipher
	}
	return ""
}

func (m *Account) GetEncryptedPrivKey() string {
	if m != nil {
		return m.EncryptedPrivKey
	}
	return ""
}

func (m *Account) GetIv() string {
	if m != nil {
		return m.Iv
	}
	return ""
}

func (m *Account) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *Account) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type PrivAccount struct {
	Alias                string   `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	PubKey               string   `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	PrivKey              string   `protobuf:"bytes,3,opt,name=priv_key,json=privKey,proto3" json:"priv_key,omitempty"`
	Expire               uint64   `protobuf:"varint,4,opt,name=expire,proto3" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivAccount) Reset()         { *m = PrivAccount{} }
func (m *PrivAccount) String() string { return proto.CompactTextString(m) }
func (*PrivAccount) ProtoMessage()    {}
func (*PrivAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *PrivAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivAccount.Unmarshal(m, b)
}
func (m *PrivAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivAccount.Marshal(b, m, deterministic)
}
func (m *PrivAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivAccount.Merge(m, src)
}
func (m *PrivAccount) XXX_Size() int {
	return xxx_messageInfo_PrivAccount.Size(m)
}
func (m *PrivAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivAccount.DiscardUnknown(m)
}

var xxx_messageInfo_PrivAccount proto.InternalMessageInfo

func (m *PrivAccount) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *PrivAccount) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *PrivAccount) GetPrivKey() string {
	if m != nil {
		return m.PrivKey
	}
	return ""
}

func (m *PrivAccount) GetExpire() uint64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func init() {
	proto.RegisterType((*Account)(nil), "protocol.Account")
	proto.RegisterType((*PrivAccount)(nil), "protocol.PrivAccount")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x95, 0xb4, 0xb5, 0xcb, 0xa0, 0xa2, 0x6a, 0x84, 0x8a, 0xd9, 0x55, 0x5d, 0x75, 0x81,
	0xd8, 0x70, 0x02, 0xd6, 0x6c, 0x50, 0x2e, 0x50, 0x39, 0x66, 0x24, 0x46, 0x94, 0x78, 0xe4, 0x26,
	0x16, 0xb9, 0x1a, 0xa7, 0x43, 0x19, 0x97, 0x1e, 0xa0, 0x2b, 0xfb, 0xfd, 0x6f, 0x8f, 0x9e, 0x0d,
	0x2b, 0x1f, 0x42, 0x1c, 0xba, 0xfe, 0x59, 0x52, 0xec, 0x23, 0x2e, 0x75, 0x09, 0xf1, 0xb8, 0xfb,
	0xad, 0xc0, 0xbe, 0x96, 0x0e, 0xef, 0x61, 0xe1, 0x8f, 0xec, 0x4f, 0xae, 0xda, 0x56, 0xfb, 0x9b,
	0xa6, 0x00, 0x3e, 0x80, 0x95, 0xa1, 0x3d, 0x7c, 0xd1, 0xe8, 0x6a, 0xcd, 0x8d, 0x0c, 0xed, 0x1b,
	0x8d, 0xb8, 0x01, 0x13, 0x58, 0x3e, 0x29, 0xb9, 0x59, 0xc9, 0x0b, 0xe1, 0x13, 0x20, 0x75, 0x21,
	0x8d, 0xd2, 0xd3, 0xc7, 0x41, 0x12, 0x67, 0xbd, 0x3b, 0xd7, 0x33, 0xeb, 0x4b, 0xf3, 0x9e, 0x38,
	0x4f, 0x53, 0xee, 0xa0, 0xe6, 0xec, 0x16, 0xda, 0xd6, 0x9c, 0x71, 0x0d, 0xb3, 0x6f, 0x1f, 0x9c,
	0xd1, 0x60, 0xda, 0xa2, 0x03, 0x9b, 0x29, 0x9d, 0x38, 0x76, 0xce, 0x6e, 0xab, 0xfd, 0xaa, 0xf9,
	0xc7, 0x5d, 0x84, 0xdb, 0x69, 0xcc, 0x95, 0xfe, 0x8f, 0xb0, 0xbc, 0xd8, 0x95, 0x17, 0x58, 0x39,
	0x4b, 0x6d, 0xc0, 0xd0, 0x8f, 0x70, 0x22, 0xd5, 0x9e, 0x37, 0x67, 0x6a, 0x8d, 0xfe, 0xdb, 0xcb,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xe4, 0xbc, 0x77, 0x4f, 0x01, 0x00, 0x00,
}
