// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HandShakeRequest struct {
	SessionId            uint64   `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandShakeRequest) Reset()         { *m = HandShakeRequest{} }
func (m *HandShakeRequest) String() string { return proto.CompactTextString(m) }
func (*HandShakeRequest) ProtoMessage()    {}
func (*HandShakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *HandShakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandShakeRequest.Unmarshal(m, b)
}
func (m *HandShakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandShakeRequest.Marshal(b, m, deterministic)
}
func (m *HandShakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandShakeRequest.Merge(m, src)
}
func (m *HandShakeRequest) XXX_Size() int {
	return xxx_messageInfo_HandShakeRequest.Size(m)
}
func (m *HandShakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandShakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandShakeRequest proto.InternalMessageInfo

func (m *HandShakeRequest) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type HandShakeResponse struct {
	SessionId            uint64   `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PubKey               string   `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	PrivKey              string   `protobuf:"bytes,3,opt,name=priv_key,json=privKey,proto3" json:"priv_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandShakeResponse) Reset()         { *m = HandShakeResponse{} }
func (m *HandShakeResponse) String() string { return proto.CompactTextString(m) }
func (*HandShakeResponse) ProtoMessage()    {}
func (*HandShakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *HandShakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandShakeResponse.Unmarshal(m, b)
}
func (m *HandShakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandShakeResponse.Marshal(b, m, deterministic)
}
func (m *HandShakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandShakeResponse.Merge(m, src)
}
func (m *HandShakeResponse) XXX_Size() int {
	return xxx_messageInfo_HandShakeResponse.Size(m)
}
func (m *HandShakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandShakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandShakeResponse proto.InternalMessageInfo

func (m *HandShakeResponse) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *HandShakeResponse) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *HandShakeResponse) GetPrivKey() string {
	if m != nil {
		return m.PrivKey
	}
	return ""
}

type Account struct {
	Alias                string   `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	PubKey               string   `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Cipher               string   `protobuf:"bytes,3,opt,name=cipher,proto3" json:"cipher,omitempty"`
	EncryptedPrivKey     string   `protobuf:"bytes,4,opt,name=encrypted_priv_key,json=encryptedPrivKey,proto3" json:"encrypted_priv_key,omitempty"`
	Iv                   string   `protobuf:"bytes,5,opt,name=iv,proto3" json:"iv,omitempty"`
	Mac                  string   `protobuf:"bytes,6,opt,name=mac,proto3" json:"mac,omitempty"`
	Version              uint32   `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Account) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *Account) GetCipher() string {
	if m != nil {
		return m.Cipher
	}
	return ""
}

func (m *Account) GetEncryptedPrivKey() string {
	if m != nil {
		return m.EncryptedPrivKey
	}
	return ""
}

func (m *Account) GetIv() string {
	if m != nil {
		return m.Iv
	}
	return ""
}

func (m *Account) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *Account) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type QueryRequest struct {
	SessionId            uint64   `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *QueryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type QueryResponse struct {
	SessionId            uint64     `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Accounts             []*Account `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{4}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *QueryResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type SaveRequest struct {
	SessionId            uint64   `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Account              *Account `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{5}
}

func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (m *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(m, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *SaveRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SaveRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type SaveResponse struct {
	SessionId            uint64   `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{6}
}

func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (m *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(m, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

func (m *SaveResponse) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *SaveResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *SaveResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*HandShakeRequest)(nil), "protocol.HandShakeRequest")
	proto.RegisterType((*HandShakeResponse)(nil), "protocol.HandShakeResponse")
	proto.RegisterType((*Account)(nil), "protocol.Account")
	proto.RegisterType((*QueryRequest)(nil), "protocol.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "protocol.QueryResponse")
	proto.RegisterType((*SaveRequest)(nil), "protocol.SaveRequest")
	proto.RegisterType((*SaveResponse)(nil), "protocol.SaveResponse")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4b, 0xab, 0xd3, 0x50,
	0x10, 0x26, 0x69, 0x9e, 0x73, 0x1f, 0xf4, 0x0e, 0x9a, 0x1b, 0x23, 0x42, 0xc8, 0x2a, 0xa0, 0x5e,
	0xf0, 0x8a, 0xe0, 0xb6, 0xe0, 0x42, 0xb9, 0x1b, 0x4d, 0x17, 0xae, 0xa4, 0x9c, 0x26, 0xa3, 0x3d,
	0xb4, 0x4d, 0x62, 0x4e, 0x12, 0xc8, 0x5f, 0x73, 0xe1, 0x6f, 0x93, 0x9c, 0x9c, 0xa6, 0xa5, 0x56,
	0x2c, 0x77, 0x37, 0xdf, 0x3c, 0xbe, 0x99, 0xf9, 0x66, 0xe0, 0xba, 0xac, 0x8a, 0xba, 0x48, 0x8b,
	0xcd, 0x9d, 0x34, 0xd0, 0xd9, 0xe1, 0xe8, 0x0d, 0x4c, 0x3f, 0xb2, 0x3c, 0x9b, 0xaf, 0xd8, 0x9a,
	0x12, 0xfa, 0xd9, 0x90, 0xa8, 0xf1, 0x05, 0x80, 0x20, 0x21, 0x78, 0x91, 0x2f, 0x78, 0xe6, 0x6b,
	0xa1, 0x16, 0x1b, 0x89, 0xab, 0x3c, 0x9f, 0xb2, 0xe8, 0x3b, 0xdc, 0x1c, 0x94, 0x88, 0xb2, 0xc8,
	0x05, 0xfd, 0xa7, 0x06, 0x6f, 0xc1, 0x2e, 0x9b, 0xe5, 0x62, 0x4d, 0x9d, 0xaf, 0x87, 0x5a, 0xec,
	0x26, 0x56, 0xd9, 0x2c, 0x1f, 0xa8, 0xc3, 0x67, 0xe0, 0x94, 0x15, 0x6f, 0x65, 0x64, 0x22, 0x23,
	0x76, 0x8f, 0x1f, 0xa8, 0x8b, 0x7e, 0x69, 0x60, 0xcf, 0xd2, 0xb4, 0x68, 0xf2, 0x1a, 0x9f, 0x80,
	0xc9, 0x36, 0x9c, 0x09, 0xc9, 0xec, 0x26, 0x03, 0xf8, 0x37, 0xab, 0x07, 0x56, 0xca, 0xcb, 0x15,
	0x55, 0x8a, 0x53, 0x21, 0x7c, 0x05, 0x48, 0x79, 0x5a, 0x75, 0x65, 0x4d, 0xd9, 0x62, 0xec, 0x6b,
	0xc8, 0x9c, 0xe9, 0x18, 0xf9, 0x3c, 0x0c, 0x80, 0xd7, 0xa0, 0xf3, 0xd6, 0x37, 0x65, 0x54, 0xe7,
	0x2d, 0x4e, 0x61, 0xb2, 0x65, 0xa9, 0x6f, 0x49, 0x47, 0x6f, 0xa2, 0x0f, 0x76, 0x4b, 0x55, 0xbf,
	0xa3, 0x6f, 0x87, 0x5a, 0x7c, 0x95, 0xec, 0x60, 0x34, 0x83, 0xcb, 0x2f, 0x0d, 0x55, 0xdd, 0x79,
	0x9a, 0x22, 0x82, 0x91, 0xb3, 0x2d, 0xa9, 0x35, 0xa4, 0x1d, 0x7d, 0x83, 0x2b, 0x45, 0x71, 0x9e,
	0xc6, 0xaf, 0xc1, 0x61, 0x83, 0x5c, 0xc2, 0xd7, 0xc3, 0x49, 0x7c, 0x71, 0x7f, 0x73, 0x37, 0xde,
	0x5d, 0x09, 0x99, 0x8c, 0x29, 0xd1, 0x16, 0x2e, 0xe6, 0xac, 0xa5, 0xc7, 0x0f, 0x88, 0x2f, 0xc1,
	0x56, 0x6c, 0x52, 0xe6, 0x93, 0xfd, 0x76, 0x19, 0xd1, 0x57, 0xb8, 0x1c, 0xda, 0x9d, 0xb7, 0x8c,
	0x07, 0x96, 0xa8, 0x59, 0xdd, 0x08, 0xd9, 0xd1, 0x49, 0x14, 0x92, 0x37, 0x10, 0x3f, 0xd4, 0x59,
	0x7b, 0xf3, 0xfe, 0xb7, 0x06, 0xe6, 0x6c, 0xc3, 0x53, 0xc2, 0x0f, 0xe0, 0x8e, 0x8f, 0x89, 0xc1,
	0x7e, 0x96, 0xe3, 0x07, 0x0f, 0x9e, 0x9f, 0x8c, 0xa9, 0xc1, 0xde, 0x83, 0x29, 0x65, 0x47, 0x6f,
	0x9f, 0x75, 0x78, 0xca, 0xe0, 0xf6, 0x2f, 0xbf, 0xaa, 0x7c, 0x07, 0x46, 0xbf, 0x22, 0x3e, 0xdd,
	0x27, 0x1c, 0x28, 0x1c, 0x78, 0xc7, 0xee, 0xa1, 0x6c, 0x69, 0x49, 0xf7, 0xdb, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xaa, 0x46, 0x0d, 0x4e, 0xa5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AliceClient is the client API for Alice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AliceClient interface {
	HandShake(ctx context.Context, in *HandShakeRequest, opts ...grpc.CallOption) (*HandShakeResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
}

type aliceClient struct {
	cc *grpc.ClientConn
}

func NewAliceClient(cc *grpc.ClientConn) AliceClient {
	return &aliceClient{cc}
}

func (c *aliceClient) HandShake(ctx context.Context, in *HandShakeRequest, opts ...grpc.CallOption) (*HandShakeResponse, error) {
	out := new(HandShakeResponse)
	err := c.cc.Invoke(ctx, "/protocol.Alice/HandShake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/protocol.Alice/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aliceClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, "/protocol.Alice/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AliceServer is the server API for Alice service.
type AliceServer interface {
	HandShake(context.Context, *HandShakeRequest) (*HandShakeResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	Save(context.Context, *SaveRequest) (*SaveResponse, error)
}

func RegisterAliceServer(s *grpc.Server, srv AliceServer) {
	s.RegisterService(&_Alice_serviceDesc, srv)
}

func _Alice_HandShake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandShakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliceServer).HandShake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Alice/HandShake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliceServer).HandShake(ctx, req.(*HandShakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alice_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Alice/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alice_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AliceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Alice/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AliceServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Alice_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Alice",
	HandlerType: (*AliceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandShake",
			Handler:    _Alice_HandShake_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Alice_Query_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _Alice_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol.proto",
}
